### ISSUE TITLE
Correct list item usage

### ISSUE THREAD

**Issue by nikitabobers** [anastasiabobere/edgeledger#1]
Tag `<li>` is 'list item'. You should use new `li` for each element. 
[documentaion](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li#:~:text=Attributes-,%3A%20The%20List%20Item%20element,usually%20displayed%20using%20bullet%20points.)
```html
<li><a>...</a></li>
<li><a>...</a></li>
...
```
https://github.com/anastasiabobere/edgeledger/blob/73c847150c4dc6840c3b5a6d427b34a1acc9922b/index.html#L43-L49

**Comment by anastasiabobere** [comment]
spasibo
